name: .NET Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # استخدم الإصدار الأحدث من .NET
    - name: Install SSDT
      run: choco install microsoft-sql-server-data-tools -y
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: msbuild /p:Configuration=Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
